server:
    prot: 8090

database: db-ocean

table:
    export:
        # 0-导出所有表 1-导出配置中的表 2-导出配置之外的其他表
        type: 0
        # 配置的表，以逗号隔开
        list:

spring:
    datasource:
        url: jdbc:mysql://192.168.88.100:3306/${database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&useAffectedRows=true&rewriteBatchedStatements=true
        username: root
        password: F@yuan5015
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml
